import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#adc6ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-error": "#ffffff",
        "on-surface-variant": "#424754",
        "secondary-fixed-dim": "#b1c6f9",
        "secondary-fixed": "#d8e2ff",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        tertiary: "#924700",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#fefcff",
        "on-primary-fixed-variant": "#004395",
        "primary-fixed-dim": "#adc6ff",
        "primary-container": "#2170e4",
        "on-background": "#191c1e",
        "surface-tint": "#005ac2",
        primary: "#0058be",
        "surface-container-high": "#e6e8ea",
        "inverse-on-surface": "#eff1f3",
        "tertiary-container": "#b75b00",
        "on-surface": "#191c1e",
        outline: "#727785",
        "on-secondary-container": "#405682",
        "on-primary-fixed": "#001a42",
        "tertiary-fixed": "#ffdcc6",
        background: "#f7f9fb",
        "on-secondary-fixed": "#001a42",
        "surface-variant": "#e0e3e5",
        "surface-container": "#eceef0",
        "surface-bright": "#f7f9fb",
        "primary-fixed": "#d8e2ff",
        surface: "#f7f9fb",
        "outline-variant": "#c2c6d6",
        "surface-dim": "#d8dadc",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#304671",
        "on-secondary": "#ffffff",
        secondary: "#495e8a",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed-variant": "#723600",
        "surface-container-low": "#f2f4f6",
        "inverse-surface": "#2d3133",
        "secondary-container": "#b6ccff",
        "tertiary-fixed-dim": "#ffb786",
        "on-tertiary-fixed": "#311400",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
};
export default config;
